### ISSUE TITLE
Does your implementation can reproduce the results reported in the MADDPG paper?

### ISSUE THREAD

**Issue by KK666-AI** [shariqiqbal2810/maddpg-pytorch#10]
Dear Author,

I notice that OpenAI has also released the source code of MADDPG. However, many researchers claimed that they cannot reproduce the results claimed in the original paper as Fig.4  (https://github.com/openai/maddpg/issues/23). I wonder whether your implementation could reproduce the results in scenario=simple_speaker_listener.

Thanks.
Hui

**Comment by shariqiqbal2810** [comment]
I haven't carefully compared the numbers, so you will have to run the code and see. Based on qualitative analysis, I believe it does.
