### ISSUE TITLE
confusing about agent.state.c.

### ISSUE THREAD

**Issue by KK666-AI** [shariqiqbal2810/maddpg-pytorch#12]
Dear Author,

In the environment, such as speaker and listener, the listener can obtain the speakers state.c as the observation, however, i don't find where the state.c is updated?

**Comment by shariqiqbal2810** [comment]
This question pertains to the code in [multiagent-particle-environments](https://github.com/openai/multiagent-particle-envs). I would recommend that you ask questions pertaining to their code in their repository in the future, as I am not the author.

The `state.c` attribute seems to be updated in [this function](https://github.com/openai/multiagent-particle-envs/blob/6ed7cac026f0eb345d4c20232bafa1dc951c68e7/multiagent/core.py#L171) by setting it to the agent's communication action plus some optional noise.
