### ISSUE TITLE
Hello! I am a graduate student at school, I have a problem running the main program, I want to ask you

### ISSUE THREAD

**Issue by dcy0324** [shariqiqbal2810/maddpg-pytorch#14]
Hello! When I run python main.py directly when running the main program, the system prompts main.py: error: the following arguments are required: env_id, model_name. Excuse me, how should I choose to enter these two parameters? Looking forward to your reply, thank you very much!

**Comment by shariqiqbal2810** [comment]
`env_id` is the name of the scenario in the multiagent-particle-environment repo. These can be viewed [here](https://github.com/shariqiqbal2810/multiagent-particle-envs/tree/master/multiagent/scenarios). `model_name` is simply a name that you give to the model that will be saved by the script.

**Comment by EvaluationResearch** [comment]
hi,
I‘m running into the following error:
    parser.add_argument("env_id", type=str, default="simple_tag", help="name of the scenario script")
    parser.add_argument("model_name", default="./model/",
                        help="Name of directory to store " +
                             "model/training contents")
main.py: error: the following arguments are required: env_id, model_name

and when simple run: python main.py --env_id simple_tag --model_name ./model/
the error will be pops up:main.py: error: unrecognized arguments: --env_id --model_name

I am not clear how to set these arguments, would you help leave me an example to add_argument run main.py?

Thanks.

**Comment by lilyleii** [comment]
> 

Hi, I meet the same problem, how do you solve it? Thanks.

**Comment by shariqiqbal2810** [comment]
They're mandatory flags, so you just enter them in the order specified without the argument name. For example:

```bash
python main.py simple_tag model_name
```
