### ISSUE TITLE
Config for demo tasks

### ISSUE THREAD

**Issue by julienroyd** [shariqiqbal2810/maddpg-pytorch#2]
Hi shariqiqbal2810,

First of all thanks a lot for sharing this great implementation. It is super clear and very enlightening! :)

Would it be possible  for you to provide some suggested config (number of training episodes, learning rates, etc.) to get the results that you showcase in the readme?

Or do you use exactly the same hyperparams than in the original paper?

I have run some scenarios with the default configs and get much worse results than you.

Thanks a lot!

**Comment by shariqiqbal2810** [comment]
Hi Julien,

Glad you're finding it useful! Try enabling discrete action spaces. The code release from OpenAI seemed to be doing so, and it helped performance in most tasks for me. I think the default settings other than that should be fine.

**Comment by shariqiqbal2810** [comment]
Closing this issue. Let me know if it hasn't been resolved and I can reopen it!
