### ISSUE TITLE
Update MultiAgentEnv construction

### ISSUE THREAD

**Issue by tessavdheiden** [shariqiqbal2810/maddpg-pytorch#22]
Hi!

Here you make an instance of the env:
https://github.com/shariqiqbal2810/maddpg-pytorch/blob/40388d7c18e4662cf23c826d97e209df9003d86c/utils/make_env.py#L47

you input a discrete_action, but this is not consistent with the multi-agent env:
https://github.com/openai/multiagent-particle-envs/blob/69ee7f85811c77ee651722bc3c332677b2195da1/multiagent/environment.py#L14

Maybe you forgot to update it?

Best,
Tessa

**Comment by shariqiqbal2810** [comment]
Hi,

I created a [fork of the particle envs](https://github.com/shariqiqbal2810/multiagent-particle-envs) which should be compatible with this code.
