### ISSUE TITLE
Avg reward different than paper

### ISSUE THREAD

**Issue by tessavdheiden** [shariqiqbal2810/maddpg-pytorch#23]
Hi!

Great repo, also neat evaluation (evaluation.py and tensorboardX in main). 

The only thing that I do not understand is why the paper Fig 4. has an average episodic reward of -20 and in tensorboard it is in the order of -2. 

Please see below Fig 4 from the paper and my tensorboard output:
![Screenshot 2020-05-28 at 14 28 07](https://user-images.githubusercontent.com/24938569/83143200-df2c3400-a0f1-11ea-832f-c70b9a73f112.png)

![Screenshot 2020-05-28 at 14 34 25](https://user-images.githubusercontent.com/24938569/83143159-cde32780-a0f1-11ea-9021-30634ddc1ea1.png)

**Comment by shariqiqbal2810** [comment]
I believe this is due to my code averaging over timesteps. To get comparable values, try multiplying by the number of timesteps per episode, which should be 25 for this environment.

**Comment by tessavdheiden** [comment]
Hi,
That is a possibility, thanks!
