### ISSUE TITLE
Benchmark and obtain table

### ISSUE THREAD

**Issue by tessavdheiden** [shariqiqbal2810/maddpg-pytorch#24]
Hi Shariq,

Great repo. The scenarios have benchmark data, but in your code and in the [tensorflow repo](https://github.com/openai/maddpg), there is no script that analyses this data. 

Also, to get the numbers for [Table 2 (Appendix)](https://arxiv.org/pdf/1706.02275.pdf), I only count the collisions once per epoch (so if agents collide multiple times, I discard it). Regarding the avg_dist, I only check the distance at the end of an episode.

Do you have any knowledge on how the numbers of Table 2 can be obtained?

**Comment by shariqiqbal2810** [comment]
Hi,

Unfortunately, I do not know how these results were calculated. I would recommend reaching out to the authors for more information.

**Comment by tessavdheiden** [comment]
Hi, just did. Thanks.
