### ISSUE TITLE
how to make the visualization (gif) using the trained model?

### ISSUE THREAD

**Issue by ptirupat** [shariqiqbal2810/maddpg-pytorch#27]
I have trained the MADDPG model and I want to visualize the results as you have shown in the repo. Do you have code to do that or can you give me pointers to how to do it from the trained model?

**Comment by vivh3** [comment]
Hi, did you happen to find a solution for this? Wondering the same thing.

**Comment by vivh3** [comment]
Hi @ptirupat, did you happen to find a solution for this? Wondering the same thing.

**Comment by ptirupat** [comment]
Use the code in evaluate.py
