### ISSUE TITLE
Problems when using Discrete Action

### ISSUE THREAD

**Issue by ryrobotics** [shariqiqbal2810/maddpg-pytorch#28]
Hi, Thanks for the pytorch version of MADDPG. I notice that it is important to use  `--discrete_action`. But when I add this option, there is something wrong.
Here is my command
`python main.py simple_tag test --discrete_action`
And there is my error

>Traceback (most recent call last):
  File "main.py", line 155, in <module>
    run(config)
  File "main.py", line 100, in run
    maddpg.update(sample, a_i, logger=logger)
  File "/home/maddpg-pytorch/algorithms/maddpg.py", line 143, in update
    curr_pol_vf_in = gumbel_softmax(curr_pol_out, hard=True)
  File "/home/maddpg-pytorch/utils/misc.py", line 88, in gumbel_softmax
    y = gumbel_softmax_sample(logits, temperature)
  File "/home/maddpg-pytorch/utils/misc.py", line 73, in gumbel_softmax_sample
    y = logits + sample_gumbel(logits.shape, tens_type=type(logits.data))
RuntimeError: expected device cuda:0 but got device cpu

I have make `USE_CUDA = True`.

Thanks for your help!

**Comment by shariqiqbal2810** [comment]
You need to make sure that the sampled variable is on the same device as the logits. The easiest thing to do would be to add `.cuda()` to the end of line 73 in `misc.py`, though this would break the code if you set `USE_CUDA = False`. The best thing to do would be to infer the device from the logits variable and set the sample to be on the appropriate device.

**Comment by ryrobotics** [comment]
Thank you very much！
