### ISSUE TITLE
Question about some arguments.

### ISSUE THREAD

**Issue by ShawnLue** [shariqiqbal2810/maddpg-pytorch#3]
Hi Shariq,

I'm a little confused about the 'n_rollout_threads' and 'n_training_threads'.

In your code, `n_rollout_threads` is set to 1. If I understand correctly, this indicates using `DummyVecEnv` without collecting experiences in parallel. Any insight why not using `SubprocVecEnv` like in a2c?

And what about `n_training_threads`? Is this setting only for acceleration?

Thanks a lot!

**Comment by shariqiqbal2810** [comment]
Hi Shawn,

`n_rollout_threads` is set to 1 by default, but you can set it to however many available threads you have on your machine. For example, I used 12.

`n_training_threads` just controls how many threads PyTorch uses for inference if you're not using a GPU.

**Comment by ShawnLue** [comment]
Thank you so much!
