### ISSUE TITLE
Problem in building env

### ISSUE THREAD

**Issue by passenger20** [shariqiqbal2810/maddpg-pytorch#30]
Hi, thank your for your public reproducing project. I just followed your guidance including downloading multi-agent environment. But there is an error when ran the main.py.
```
File "/home/l/anaconda3/lib/python3.7/site-packages/gym/core.py", line 64, in reset
    raise NotImplementedError
NotImplementedError
```
Looking forward to your reply.

**Comment by FabianSchuetze** [comment]
I faced the same issue. I have changed the code to 
```Python
results = [env._reset() for env in self.envs]
```
in line 140 of [utils/env_wrappers.py](https://github.com/shariqiqbal2810/maddpg-pytorch/blob/master/utils/env_wrappers.py) as `_reset` is a function present in `multiagent-particle-envs` but I am not sure if this is correct. 

Do you have any guidance on this @shariqiqbal2810  ? That would be wonderful to hear!

**Comment by shariqiqbal2810** [comment]
Are you using the gym version specified in the README?

**Comment by FabianSchuetze** [comment]
Thank you, @shariqiqbal2810  . I initially did not use the correct version you mentioned. After I changed version the problem was resolved.

**Comment by azyslzp** [comment]
> Thank

Hi, I also met the same problem , how you solved this issue, thanks a lot~

**Comment by azyslzp** [comment]
> Thank you, @shariqiqbal2810 . I initially did not use the correct version you mentioned. After I changed version the problem was resolved.

     

Hi, I also met the same problem , how you solved this issue, thanks a lot~
