### ISSUE TITLE
Hi, i got a problem when i try to excute main.py

### ISSUE THREAD

**Issue by rookiedali** [shariqiqbal2810/maddpg-pytorch#40]
The log is  as follows:
```
$ python main.py simple_push push_model
E:\anaconda\lib\site-packages\gym\logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Episodes 1-2 of 25000
Traceback (most recent call last):
  File "main.py", line 166, in <module>
    run(config)
  File "main.py", line 72, in run
    obs = env.reset()
  File "D:\GithubProject\py\maddpg-pytorch-master\utils\env_wrappers.py", line 125, in reset
    results = [env.reset() for env in self.envs]
  File "D:\GithubProject\py\maddpg-pytorch-master\utils\env_wrappers.py", line 125, in <listcomp>
    results = [env.reset() for env in self.envs]
  File "E:\anaconda\lib\site-packages\gym\core.py", line 66, in reset
    raise NotImplementedError
NotImplementedError
```
what's wrong with the notimplementedError, Thank you very much for your answer！

**Comment by Milad-Rakhsha** [comment]
I am getting a similar error, would greatly appreciate any help

**Comment by shariqiqbal2810** [comment]
Are you using the package versions specified in the README?

**Comment by rookiedali** [comment]
> Are you using the package versions specified in the README?

Thanks for your answer, i solve it by change the private method in the file envirment.py to the common method. Although I don't know the specific reason, it works！

**Comment by rookiedali** [comment]
> I am getting a similar error, would greatly appreciate any help

Maybe you can try to change the private method in the file envirment.py to the common method, that is _step -> step,  _reset->reset and so on
