### ISSUE TITLE
env problem

### ISSUE THREAD

**Issue by GELIELEO** [shariqiqbal2810/maddpg-pytorch#5]
cooperative communication env did not work.
return as follow:

Traceback (most recent call last):
  File "main.py", line 155, in <module>
    run(config)
  File "main.py", line 57, in run
    hidden_dim=config.hidden_dim)
  File "/home/nuc/causal_ws/maddpg-pytorch/algorithms/maddpg.py", line 256, in init_from_env
    num_in_critic += get_shape(oacsp)
  File "/home/nuc/causal_ws/maddpg-pytorch/algorithms/maddpg.py", line 249, in <lambda>
    get_shape = lambda x: x.n
AttributeError: 'Box' object has no attribute 'n'

**Comment by KK666-AI** [comment]
@GELIELEO  I also meet this error. How to solve it?

**Comment by shariqiqbal2810** [comment]
@lihuiknight  Use the flag `--discrete_action` so that all agents have the same type of action space

**Comment by Sobbbbbber** [comment]
How to solve it? I haven't understand it >_<

**Comment by shariqiqbal2810** [comment]
@Sobbbbbber When you run the script, include the flag `--discrete_action`

For example:
`python main.py simple_speaker_listener model_name --discrete_action`

**Comment by Sobbbbbber** [comment]
@shariqiqbal2810 thank you for your reply~ It does work :)
