### ISSUE TITLE
Does shared weights among actors matter?

### ISSUE THREAD

**Issue by andrewliao11** [shariqiqbal2810/maddpg-pytorch#8]
Hi @shariqiqbal2810, thanks for the nice implementation.
I spotted a difference between your implementation and the official one. In the official code (@openai/maddpg), the actors' weights are shared, while your implementation does not. 

Do you spot any difference? Such as unstable learning, slow convergence, or more diverse behavior.
Thanks in advance.

**Comment by shariqiqbal2810** [comment]
I haven't run the code side by side with the official implementation, but, in general, I have found that sharing weights leads to less diverse behavior (even when an agent index is passed in as input to the policies).

I also briefly looked at the official code, and it doesn't seem like the actor weights are shared as far as I can tell. It looks like the function `mlp_model` is passed into a separate `MADDPGAgentTrainer` for each agent which instantiates a separate model using this function for each agent.
