### ISSUE TITLE
what's black block stand for?

### ISSUE THREAD

**Issue by KK666-AI** [shariqiqbal2810/maddpg-pytorch#9]
Dear author,

your project is helpful to the research community. just want to ask what are the black blocks in predator-prey? some forbidden areas for both predator and prey?

**Comment by shariqiqbal2810** [comment]
From the MADDPG [paper](https://arxiv.org/pdf/1706.02275.pdf):

> In this variant of the classic predator-prey game, N slower cooperating agents must chase the faster adversary around a randomly generated environment with L large landmarks impeding the way. Each time the cooperative agents collide with an adversary, the agents are rewarded while the adversary is penalized. Agents observe the relative positions and velocities of the agents, and the positions of the landmarks.

The black blocks are the landmarks. Presumably they are included to make the problem more interesting (e.g. prey can use landmarks to block the path of predators)
